name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    run-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up env
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: install dependencies
        run: npm install

      - name: build the app
        run: npm run build
